### ISSUE TITLE
Handling of re-importing geometry with same group naming convention

### ISSUE THREAD

**Issue by Polymega** [pmttavara/ph2#9]
From your discussion over at Discord:

> The behaviour of “Import OBJ” has now changed due to the grouping feature. The import currently does NOT look at which mesh category is highlighted in the tool. The reason you saw the OBJ model import into the category you had selected, was because the importer detected the annotations in the OBJ file specifying that exact group in the map.
> 
> Right now, the OBJ exporter and importer always identify and utilize grouping information. So, for example, if you export Geometry #3, Mesh #2, then that #3 and #2 will be engraved into the OBJ file (in the obj group names…) and when you re-import that OBJ file (or an edited re-exported version of the OBJ file from Blender or Maya with lightly touched obj group names) it will see “Geometry #3, Mesh #2” and intentionally re-insert that part of the model into geometry #3 mesh #2. 

Before I realized this, when I was previously re-importing geometry with the same group naming convention, what would typically happen is the tool would simply duplicate the geometry within that master group. Basically there'd be two, exact instances of the same geometry, then.

However, I did find that with `cb12.map`, for example, if you export the geometry and re-import it the tool will crash to desktop, instead of "duplicating" the geometry within that same master group as mentioned prior.

https://github.com/pmttavara/ph2/assets/27395260/54ef0262-8c94-4c92-aadc-f87fa30dc8f6

Interestingly, at least with `cb12.map`, this crash only happens when trying to re-import an **Opaque Mesh** master group. It doesn't crash with **Transparent** or **Decal**. With **Transparent** and **Decal**, the tool imports them as "duplicated", as mentioned prior.

Seemingly being an issue with **Opaque** only, I wonder if there's any similarities with this? https://github.com/pmttavara/ph2/issues/8

Now, I can simply be mindful to try and not import like this, but I felt it's worth bringing to your attention, specially due to it sometimes crashing to desktop. I suppose a question to ask about this is: Would checks or fail safes be desired to help with such a predicament?

**Comment by pmttavara** [comment]
(GitHub auto-closed this issue -- Reopen it if you still hit this crash!)

Thanks for catching this. Looks like I hadn't been checking against any limits for the number of indices you can put in a mesh (I have it set to 100,000, which is ~40% more than the biggest mesh in all of the stock maps, but this limit was being overflowed and breaking things).

I've added limit checks that will print to the console describing which limits were reached (either vertex limit or index limit). See the yellow text in the console in this screenshot.

![image](https://github.com/pmttavara/ph2/assets/34119228/2b6d474f-d690-44d6-ac18-cfd5c8d05480)

It's a little bit confusing because the limit checks are per-OBJ-group, so if there's a group later on that only needs 1000 more indices, it *can* fit inside the mesh it requested, but some other group that needs 4000 indices might not fit and have to allocate a new mesh. So a set of OBJ groups that all wanted to be inside a specific mesh can alternate between fitting inside that mesh and spilling out to allocating a new mesh. Not great!

Hope this works to address it.

**Comment by Polymega** [comment]
That did the trick! No more crashes! Thank you so much
